services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example_pw
      POSTGRES_DB: OrdersDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d OrdersDb"]
      interval: 5s
      timeout: 3s
      retries: 10
  
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: ./OrderProcessingService/Dockerfile
    container_name: orderprocessing-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      RabbitMQ__HostName: "amqp://guest:guest@rabbitmq:5672/"
      MessageQueues__Queues__Orders: "order-rabbit-mq"
      ConnectionStrings__OrdersDb: "Host=postgres;Port=5432;Database=OrdersDb;Username=postgres;Password=example_pw;SSL Mode=Disable"
    ports:
      - "8080:8080"
  
  worker:
    build:
      context: .
      dockerfile: ./OrderProcessingService.Worker/Dockerfile
    container_name: orderprocessing-worker
    restart: unless-stopped
    depends_on:
      api:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      RabbitMQ__HostName: "amqp://guest:guest@rabbitmq:5672/"
      MessageQueues__Queues__Orders: "order-rabbit-mq"
      Metrics__Port: "9100"
      ConnectionStrings__OrdersDb: "Host=postgres;Port=5432;Database=OrdersDb;Username=postgres;Password=example_pw;SSL Mode=Disable"
    ports:
      - "9100:9100"
  
  prometheus:
    image: prom/prometheus:v2.55.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      worker: 
        condition: service_started

volumes:
  pgdata:
  rabbitmq_data: